### ISSUE TITLE
Version issues

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7278]
Hi,

The Zeebe docker compose version I have is 1.0.

The client dependency I am working with is 0.26.0 because I can´t find more. Due to this, I have issues using some methods for deployment. What dependency can I use or what updated version to avoid this issue?

Thank you

**Comment by npepinpe** [comment]
Which client are you using? If you're using the Java client, you can use `io.camunda:zeebe-client-java:1.0.0`. See https://search.maven.org/artifact/io.camunda/zeebe-client-java/1.0.0/jar

**Comment by nachoroncero** [comment]
Hello, thanks for you reply,

Yes, I am using the Java Cliente. I changed to the dependency you said but
now it looks like any method cannot be found... the Zeebeclient and
deploymentEvent methods  cannot be found

**Comment by Lzgabel** [comment]
Hi @nachoronce, since version 1.0.0, workflow has been renamed to process. [#6843](https://github.com/camunda-cloud/zeebe/pull/6843)

**Comment by nachoroncero** [comment]
Ok, thank you. It works.

Now, in the next step: create an instance, it says that cannot find symbol:
WorkflowInstanceEvent… is there any change here?

**Comment by Lzgabel** [comment]
https://github.com/camunda-cloud/zeebe/issues/7277#issuecomment-860857999

workflowInstance -> processInstance

**Comment by nachoroncero** [comment]
Now it is:

Final WorkflowInstanceEvent wfinstance = client.newCreateInstanceCommand()…

How would it be for version 1.0.0?

**Comment by Lzgabel** [comment]
> workflowInstance -> processInstance

WorkflowInstanceEvent  -> ProcessInstanceEvent

**Comment by nachoroncero** [comment]
Thank you, now I have no exceptions, but when I go to localhost:8082 to see
the monitor, there are no instances created… I don’t know why because the
code is exactly the same as in the instructions, I only changed the methods
we talked

**Comment by nachoroncero** [comment]
so?

**Comment by jwulf** [comment]
Or ask in the Forum - that has more eyeballs on it than individual repositories: [https://forum.camunda.io](https://forum.camunda.io).
